---
default_language_version:
  python: python3.11

exclude: '^(static\/css\/bootstrap\/.(.+)|static\/js\/bootstrap\/.(.+)|(.+)/migrations/(.+))'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        name: djhtml
        args:
          - --tabwidth=2

#  - repo: https://github.com/thibaudcolas/curlylint
#    rev: v0.13.1
#    hooks:
#      - id: curlylint
#        name: curlylint

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.19.0
    hooks:
      - id: django-upgrade
        name: django-upgrade
        args: [ --target-version, "5.0" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args: [ --py311-plus ]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-no-pep420
          - flake8-comprehensions
          - flake8-docstrings

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.1'
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies:
          - django-cleanup
          - django-debug-toolbar
          - django-stubs
          - mypy-extensions
          - python-dotenv
          - types-requests
          - typing_extensions
          - types-python-dateutil
