[project]
name = "devfaq-com"
version = "0.1.0"
description = "Devfaq, a site to answer those burning dev questions."
keywords = ["devfaq", "programming", "development"]
authors = [{ name = "Peter McDonald", email = "admin@rockprofile.com"}]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==6.0.3",
    "django-cleanup>=9.0.0",
    "django-debug-toolbar>=6.3.0",
    "pillow>=12.2.0",
    "psycopg2>=2.9.11",
    "pygments>=2.20.0", # To resolve security vulnerabilities in dependencies pytest, rich
    "python-dotenv>=1.2.2",
]

classifiers = [
  "Framework :: Django",
  "Framework :: Django :: 6",
  "Framework :: Django :: 6.0",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]

[project.urls]
homepage = "https://devfaq.com/"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.0.0",
    "pytest-mypy-plugins>=3.2.0",
    "ruff>=0.14.10",
    "troml>=0.4.1",
    "ty>=0.0.9",
]

[tool.ruff]
line-length = 120
