sonar.projectKey=RockProfile_devfaq.com_c030c2ec-1a09-436a-aace-eb1b09cc06b8
sonar.sources=.
sonar.exclusions=static/**/bootstrap*, static/**/htmx*, venv/**/*, **/migrations/*, .env
sonar.python.version=3.13
