# Generated by Django 5.1.1 on 2024-09-15 09:46

import django.db.models.deletion
import website.models
import website.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BiographyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('biography', models.CharField(max_length=1000)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=20, unique=True, validators=[website.validators.subdomain_validator])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=website.models.logo_file_name, validators=[website.validators.file_size_validator])),
                ('live', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PluginContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateField(auto_now_add=True)),
                ('plugin', models.CharField(choices=[('article', 'Article'), ('calendar', 'Calendar'), ('faq', 'FAQ'), ('featured_function', 'Featured Function'), ('featured_package', 'Featured Package'), ('news', 'News')], max_length=100)),
                ('content', models.JSONField(default=dict)),
                ('draft', models.BooleanField(default=False)),
                ('for_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('random_validation_string', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('mastodon', 'Mastodon'), ('x', 'X')], max_length=20)),
                ('handle', models.CharField(max_length=100)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'for_user'), name='unique_socials')],
            },
        ),
    ]
