#!/bin/sh

cd /site || exit

/bin/curl -LsSf https://astral.sh/uv/install.sh | sh
/root/.local/bin/uv run manage.py
/root/.local/bin/uv run manage.py makemigrations
/root/.local/bin/uv run manage.py migrate
/root/.local/bin/uv run manage.py createsuperuser --no-input
/root/.local/bin/uv run manage.py runserver 0.0.0.0:8080
